### ISSUE TITLE
Version 0.63 TODO

### ISSUE THREAD

**Issue by EmperorArthur** [mlox/mlox#28]
These are what needs to be done before Version 0.63 is released.

- [x] Switch to Python3
- [x] Move to Qt5 GUI
- [ ] Have the updater's extraction be self contained (don't rely on 7za)
- [ ] Store mlox_base.txt and mlox_user.txt in AppData (so mlox can be made read only, or packaged to a single exe with an auto extractor)
- [ ] Add a GUI option to open the AppData folder (so people can easily access mlox_user.txt)
- [ ] Enable writing to OpenMW.cfg files
- [ ] Add GUI options to modify the Data Directory, and ini file location.
- [ ] Add a command line switch to set the data file directory

Python3 is a future proofing move, and also allows for newer libraries.  Things like self contained extraction require it.  There's also a new Path library, that looks interesting.

The Qt5 GUI re-write mostly came from the pain of trying to get wxPython working with Python3.  It was honestly easier to re-write it than it was to just debug why pip3 was failing.  The fact Qt5 is a modern multiplatform toolkit, and QtCreator means I can get a real time preview of what the GUI looks like are nice bonuses.

Version 0.62 of Mlox couldn't ship as a single EXE because all the single EXE compilers really just bundled everything up into a self extracting exe.  Since they extracted to a temp directory, Mlox had to constantly re-download mlox_base.txt, and mlox_user.txt couldn't be used.  Swapping to AppData solves these issues.  Plus, it means Mlox can be installed in Windows "Program Files" directory, where apps aren't allowed to write to their own directory.

I never was a fan of having to ship 7za.exe.  It just feels hacky, and then there's the whole having to make sure the license is adhered to thing.

OpenMW support is a huge deal.  While we can currently read from the config file, we can't currently write to it.  Being able to do so means we're one step closer to that goal.

Even if the program can't currently auto detect the OpenMW file, having a GUI option, and a command line switch means we can at least manually get everything working.  No more import wizard for OpenMW users!

**Comment by EmperorArthur** [comment]
When I have more time: `xdg-open` will work for opening 'mlox_user.txt' and the AppData equivalent in Linux.  Either `Invoke-Item` or `start` should work for windows.  I hate having to add OS dependent checks, but in this case it may be unavoidable.
